version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: <project>_nginx
    ports:
      - "80:8000" # web
      - "443:8443"
    volumes: &appvolumes
      - ./src/app/code:/var/www/html/app/code:delegated
      - ./src/app/design:/var/www/html/app/design:delegated
      - ./src/app/etc:/var/www/html/app/etc:delegated
      - ~/.composer:/var/www/.composer:delegated
      - ./src/composer.json:/var/www/html/composer.json:delegated
      - ./src/composer.lock:/var/www/html/composer.lock:delegated
      - ~/.npm:/var/www/.npm
      - <project>_sockdata:/sock
    depends_on:
      - db
    links:
      - db
      - phpfpm
    networks:
      - <project>-network

  phpfpm:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: <project>_phpfpm
    volumes: *appvolumes
    links:
      - db
    networks:
      - <project>-network

  db:
    image: mariadb
    container_name: <project>_db
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=magento
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
      - ./src:/home
    networks:
      - <project>-network

  redis:
    image: redis
    container_name: <project>_redis
    ports:
     - 6379
    networks:
      - <project>-network

  redis-session:
    image: redis
    container_name: <project>_redis-session
    ports:
     - 6379
    networks:
      - <project>-network

  mailhog:
    image: mailhog/mailhog
    container_name: <project>_mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - <project>-network

  elasticsearch:
    image: elasticsearch:6.8.1
    container_name: <project>_elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - <project>-network

networks:
  <project>-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  <project>_sockdata:
